import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Topnav from '../components/topnav'
import SideNav from '../components/sidenav'
import { Bar } from 'react-chartjs-2/dist/typedCharts'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Teck-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Topnav/>
      <SideNav/>
      <Bar data={data} />

      </main>
    </>
  )
}
