import Head from 'next/head'
import { Inter } from '@next/font/google'
import Topnav from '../components/topnav'
import SideNav from '../components/sidenav'
import { FunnelChart } from 'recharts/types/chart/FunnelChart'
import Averageschart from '../components/avg-chart'
import Fuelchart from '../components/fuel-mile-chart'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Teck-App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='color-s'>
      <Topnav/>
      <div className='flex'>
        <SideNav/>
          <div className='border-2 rounded-lg'>
            <Averageschart/>
          </div>
          <div className='border-2 rounded-lg'>
            <Fuelchart/>
          </div>
      </div>

      </main>
    </>
  )
}
