# Generated by Django 4.1.5 on 2023-01-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckSensorData',
            fields=[
                ('log_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField()),
                ('gps_northing', models.FloatField()),
                ('gps_easting', models.FloatField()),
                ('gps_elevation', models.FloatField()),
                ('fuel_rate', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('payload', models.FloatField()),
                ('truck_id', models.PositiveIntegerField()),
                ('truck_type_id', models.PositiveIntegerField()),
                ('shovel_id', models.PositiveIntegerField()),
                ('dump_id', models.PositiveIntegerField()),
                ('rnd', models.PositiveIntegerField()),
            ],
        ),
    ]
