# Generated by Django 4.1.5 on 2023-01-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trucksensordata',
            name='fuel_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucksensordata',
            name='gps_easting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucksensordata',
            name='gps_elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucksensordata',
            name='gps_northing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trucksensordata',
            name='payload',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
